CROPS = {
    "carrot": {"min_temp": 7, "frost_sensitive": False, "sow_months": (3, 7)},
    "beetroot": {"min_temp": 7, "frost_sensitive": False, "sow_months": (3, 7)},
    "parsnip": {"min_temp": 6, "frost_sensitive": False, "sow_months": (2, 4)},
    "turnip": {"min_temp": 6, "frost_sensitive": False, "sow_months": (3, 8)},
    "swede": {"min_temp": 6, "frost_sensitive": False, "sow_months": (5, 6)},
    "radish": {"min_temp": 6, "frost_sensitive": False, "sow_months": (3, 9)},
    "potato": {"min_temp": 8, "frost_sensitive": True, "sow_months": (3, 5)},
    "lettuce": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 9)},
    "spinach": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 9)},
    "rocket": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 9)},
    "chard": {"min_temp": 7, "frost_sensitive": False, "sow_months": (4, 7)},
    "kale": {"min_temp": 5, "frost_sensitive": False, "sow_months": (4, 6)},
    "cabbage": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 5)},
    "cauliflower": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 5)},
    "broccoli": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 5)},
    "brussels sprout": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 4)},
    "kohlrabi": {"min_temp": 6, "frost_sensitive": False, "sow_months": (4, 7)},
    "pea": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 6)},
    "broad bean": {"min_temp": 5, "frost_sensitive": False, "sow_months": (2, 4)},
    "runner bean": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "french bean": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "onion": {"min_temp": 7, "frost_sensitive": False, "sow_months": (3, 4)},
    "shallot": {"min_temp": 5, "frost_sensitive": False, "sow_months": (2, 3)},
    "garlic": {"min_temp": 0, "frost_sensitive": False, "sow_months": (10, 11)},
    "leek": {"min_temp": 7, "frost_sensitive": False, "sow_months": (3, 4)},
    "courgette": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "pumpkin": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "squash": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "cucumber": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "sweetcorn": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "tomato": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "pepper": {"min_temp": 14, "frost_sensitive": True, "sow_months": (5, 6)},
    "chilli": {"min_temp": 14, "frost_sensitive": True, "sow_months": (5, 6)},
    "aubergine": {"min_temp": 14, "frost_sensitive": True, "sow_months": (5, 6)},
    "celery": {"min_temp": 8, "frost_sensitive": False, "sow_months": (4, 5)},
    "celeriac": {"min_temp": 8, "frost_sensitive": False, "sow_months": (4, 5)},
    "fennel": {"min_temp": 8, "frost_sensitive": False, "sow_months": (4, 6)},
    "asparagus": {"min_temp": 5, "frost_sensitive": False, "sow_months": (4, 5)},
    "rhubarb": {"min_temp": 0, "frost_sensitive": False, "sow_months": (11, 3)},
    "basil": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "coriander": {"min_temp": 8, "frost_sensitive": False, "sow_months": (4, 8)},
    "parsley": {"min_temp": 7, "frost_sensitive": False, "sow_months": (3, 7)},
    "dill": {"min_temp": 8, "frost_sensitive": False, "sow_months": (4, 7)},
    "mint": {"min_temp": 5, "frost_sensitive": False, "sow_months": (4, 6)},
    "thyme": {"min_temp": 8, "frost_sensitive": False, "sow_months": (5, 6)},
    "chives": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 5)},
    "wheat": {"min_temp": 3, "frost_sensitive": False, "sow_months": (9, 11)},
    "barley": {"min_temp": 3, "frost_sensitive": False, "sow_months": (9, 10)},
    "oats": {"min_temp": 3, "frost_sensitive": False, "sow_months": (2, 4)},
    "rye": {"min_temp": 2, "frost_sensitive": False, "sow_months": (9, 10)},
    "triticale": {"min_temp": 3, "frost_sensitive": False, "sow_months": (9, 10)},
    "spelt": {"min_temp": 3, "frost_sensitive": False, "sow_months": (9, 10)},
    "maize": {"min_temp": 12, "frost_sensitive": True, "sow_months": (5, 6)},
    "oilseed rape": {"min_temp": 5, "frost_sensitive": False, "sow_months": (8, 9)},
    "sugar beet": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 4)},
    "field bean": {"min_temp": 3, "frost_sensitive": False, "sow_months": (10, 11)},
    "linseed": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 4)},
    "strawberry": {"min_temp": 5, "frost_sensitive": False, "sow_months": (3, 4)},
    "raspberry": {"min_temp": 2, "frost_sensitive": False, "sow_months": (11, 3)},
    "blackcurrant": {"min_temp": 2, "frost_sensitive": False, "sow_months": (11, 3)},
    "gooseberry": {"min_temp": 2, "frost_sensitive": False, "sow_months": (11, 3)},
    "blueberry": {"min_temp": 3, "frost_sensitive": False, "sow_months": (10, 3)},
    "apple": {"min_temp": 3, "frost_sensitive": False, "sow_months": (11, 3)},
    "pear": {"min_temp": 3, "frost_sensitive": False, "sow_months": (11, 3)},
    "plum": {"min_temp": 3, "frost_sensitive": False, "sow_months": (11, 3)},
    "cherry": {"min_temp": 3, "frost_sensitive": False, "sow_months": (11, 3)},
    "grape": {"min_temp": 8, "frost_sensitive": False, "sow_months": (3, 4)},
}

SYNONYMS = {
    "spud": "potato",
    "spuds": "potato",
    "tater": "potato",
    "taters": "potato",
    "corn": "sweetcorn",
    "sweet corn": "sweetcorn",
    "zucchini": "courgette",
    "eggplant": "aubergine",
    "arugula": "rocket",
    "rutabaga": "swede",
    "spring onion": "onion",
    "scallion": "onion",
    "beet": "beetroot",
    "beets": "beetroot",
    "sprout": "brussels sprout",
    "sprouts": "brussels sprout",
    "cauli": "cauliflower",
    "osr": "oilseed rape",
    "rape": "oilseed rape",
    "chili": "chilli",
    "capsicum": "pepper",
    "silverbeet": "chard",
    "swiss chard": "chard",
}
